services:
  postgres:
    restart: unless-stopped
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: pypatsy
      POSTGRES_PASSWORD: pypatsy
      POSTGRES_USER: pypatsy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pypatsy"]
      interval: 2s
      timeout: 1s
      retries: 5

  patsy:
    restart: unless-stopped
    privileged: false
    read_only: true  # Prod uses a read-only fs, override this locally if it helps with debugging
    user: "65534"  # Prod uses a non-root user, override this locally if it helps with debugging
    build: .
    command: ["alembic upgrade head && uvicorn patsy:app --host 0.0.0.0 --port 80 --reload"]
    volumes:
      - .:/patsy:ro
      - ./alembic_conf/versions:/patsy/alembic_conf/versions
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgresql+asyncpg://pypatsy:pypatsy@postgres:5432/pypatsy
      SECRET_KEY: suitable-for-development-only
      DEBUG: "true"
