[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[tool.poetry]
name = "Patsy"
version = "0.1.0"
description = "Transforms and stores help system message content for future processing."
authors = ["Python Discord <info@pythondiscord.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.10.*"

alembic = "1.8.1"
asyncpg = "0.26.0"
fastapi = "0.85.0"
httpx = "0.23.0"
loguru = "0.6.0"
sqlmodel = "0.0.8"
uvicorn = {extras = ["standard"], version = "0.18.3"}
tomlkit = "0.11.5"

[tool.poetry.dev-dependencies]
flake8 = "5.0.4"
flake8-annotations = "2.9.1"
flake8-bugbear = "22.9.23"
flake8-docstrings = "1.6.0"
flake8-isort = "5.0.0"
flake8-string-format = "0.3.0"
flake8-tidy-imports = "4.8.0"
flake8-todo = "0.7.0"
pep8-naming = "0.13.2"
pre-commit = "2.20.0"
taskipy = "1.10.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
lint = "pre-commit run --all-files"
precommit = "pre-commit install"
revision = "docker-compose exec patsy alembic revision --autogenerate -m"

[tool.isort]
multi_line_output = 6
order_by_type = false
case_sensitive = true
combine_as_imports = true
line_length = 120
known_first_party = ["patsy"]
atomic = true
