[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[tool.poetry]
name = "Patsy"
version = "0.1.0"
description = "Transforms and stores help system message content for future processing."
authors = ["Python Discord <info@pythondiscord.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

sqlmodel = "^0.0"
asyncpg = "^0.24"
alembic = "^1.7.4"
uvicorn = {extras = ["standard"], version = "^0.15"}
fastapi = "^0.70"
httpx = "^0.20"
tomlkit = "^0.7"
loguru = "^0.5"

[tool.poetry.dev-dependencies]
flake8 = "^4.0"
flake8-annotations = "^2.7"
flake8-bugbear = "^21.9"
flake8-docstrings = "^1.6"
flake8-isort = "^4.1"
flake8-string-format = "^0.3"
flake8-tidy-imports = "^4.5"
flake8-todo = "^0.7"
pep8-naming = "^0.12"
pre-commit = "^2.15"
taskipy = "^1.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
lint = "pre-commit run --all-files"
precommit = "pre-commit install"
revision = "docker-compose exec patsy alembic revision --autogenerate -m"

[tool.isort]
multi_line_output = 6
order_by_type = false
case_sensitive = true
combine_as_imports = true
line_length = 120
known_first_party = ["patsy"]
atomic = true
