[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[tool.poetry]
name = "Patsy"
version = "0.0.1"
description = "Transforms and stores help system message content for future processing."
authors = ["Python Discord <info@pythondiscord.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.9.*"
sqlmodel = "^0.0.4"
uvicorn = {extras = ["standard"], version = "^0.15.0"}
fastapi = "^0.68"
httpx = "^0.19"
jinja2 = "^3.0"
aiofiles = "^0.7"
starlette-discord = "^0.1"
itsdangerous = "^2.0"
tomlkit = "^0.7"
loguru = "^0.5"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
flake8-annotations = "^2.6"
flake8-bugbear = "^21.9"
flake8-docstrings = "^1.6"
flake8-import-order = "^0.18"
flake8-string-format = "^0.3"
flake8-tidy-imports = "^4.3"
flake8-todo = "^0.7"
pep8-naming = "^0.11"
pre-commit = "^2.13"
taskipy = "^1.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
lint = "pre-commit run --all-files"
precommit = "pre-commit install"
