"""
Add channel_id and indexing to message table.

Revision ID: 45500e513d4a
Revises: 76bffa9d07db
Create Date: 2021-11-13 22:48:38.239877
"""
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

#  Revision identifiers, used by Alembic.
revision = '45500e513d4a'
down_revision = '76bffa9d07db'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade the connected DB to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('channel_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade the connected DB to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_column('messages', 'channel_id')
    # ### end Alembic commands ###
