"""
Setup initial tables.

Revision ID: 7efb7499ead4
Revises:
Create Date: 2021-11-07 20:26:55.089834
"""
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

#  Revision identifiers, used by Alembic.
revision = '7efb7499ead4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade the connected DB to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('opted_out', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_opted_out'), 'users', ['opted_out'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table(
        'help_sessions',
        sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('session_id', sa.Integer(), nullable=True),
        sa.Column('claimant_id', sa.Integer(), nullable=False),
        sa.Column('channel_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['claimant_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_help_sessions_channel_id'), 'help_sessions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_help_sessions_claimant_id'), 'help_sessions', ['claimant_id'], unique=False)
    op.create_index(op.f('ix_help_sessions_session_id'), 'help_sessions', ['session_id'], unique=False)
    op.create_table(
        'messages',
        sa.Column('message_id', sa.Integer(), nullable=True),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
        sa.ForeignKeyConstraint(['session_id'], ['help_sessions.session_id'], ),
        sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_author_id'), 'messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_messages_content'), 'messages', ['content'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade the connected DB to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_content'), table_name='messages')
    op.drop_index(op.f('ix_messages_author_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_help_sessions_session_id'), table_name='help_sessions')
    op.drop_index(op.f('ix_help_sessions_claimant_id'), table_name='help_sessions')
    op.drop_index(op.f('ix_help_sessions_channel_id'), table_name='help_sessions')
    op.drop_table('help_sessions')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_opted_out'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
