"""
Initial help post structure.

Revision ID: b2c25a180f63
Revises:
Create Date: 2022-12-13 14:02:32.217076+00:00
"""
import sqlalchemy as sa
from alembic import op

#  Revision identifiers, used by Alembic.
revision = "b2c25a180f63"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("opted_out", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("user_id", name=op.f("users_pk")),
    )
    op.create_table(
        "help_sessions",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("claimant_id", sa.Integer(), nullable=True),
        sa.Column("opened_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["claimant_id"], ["users.user_id"], name=op.f("help_sessions_claimant_id_users_fk")),
        sa.PrimaryKeyConstraint("post_id", name=op.f("help_sessions_pk")),
    )
    op.create_table(
        "messages",
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.String(length=4000), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["users.user_id"], name=op.f("messages_author_id_users_fk")),
        sa.ForeignKeyConstraint(["post_id"], ["help_sessions.post_id"], name=op.f("messages_post_id_help_sessions_fk")),
        sa.PrimaryKeyConstraint("message_id", name=op.f("messages_pk")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_table("help_sessions")
    op.drop_table("users")
    # ### end Alembic commands ###
