"""
Initial help post structure.

Revision ID: 654fe0002a6a
Revises:
Create Date: 2023-02-19 20:30:11.224477+00:00
"""
import sqlalchemy as sa
from alembic import op

#  Revision identifiers, used by Alembic.
revision = "654fe0002a6a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("opted_out", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("users_pk")),
    )
    op.create_table(
        "help_posts",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("claimant_id", sa.Integer(), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["claimant_id"], ["users.user_id"], name=op.f("help_posts_claimant_id_users_fk")),
        sa.PrimaryKeyConstraint("post_id", name=op.f("help_posts_pk")),
    )
    op.create_table(
        "messages",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("in_reply_to_message_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(length=4000), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.user_id"], name=op.f("messages_author_id_users_fk")),
        sa.ForeignKeyConstraint(
            ["in_reply_to_message_id"],
            ["messages.message_id"],
            name=op.f("messages_in_reply_to_message_id_messages_fk"),
        ),
        sa.ForeignKeyConstraint(["post_id"], ["help_posts.post_id"], name=op.f("messages_post_id_help_posts_fk")),
        sa.PrimaryKeyConstraint("message_id", name=op.f("messages_pk")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_table("help_posts")
    op.drop_table("users")
    # ### end Alembic commands ###
